import { CommonModule } from "@angular/common";
import { Component, output, Output, signal } from "@angular/core";
import { Chat } from "../../../shared/models/chat.interface";
import { UserRole } from "../../../shared/models/user.interface";
import { ProfilePhoto } from "../../misc/profile-photo/profile-photo";

@Component({
    selector: 'taleemiyat-session-chat',
    templateUrl: './session-chat.html',
    standalone: true,
    imports: [CommonModule, ProfilePhoto],
})
export default class SessionChat {
    closeChat = output<boolean>();
    chatMessages = signal<Partial<Chat>[]>([
        {
            id: '1',
            senderId: '1',
            receiverId: '2',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '1',
                email: 'john.doe@example.com',
                username: 'john.doe',
                firstName: 'John',
                lastName: 'Doe',
                role: UserRole.STUDENT,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
        {
            id: '2',
            senderId: '2',
            receiverId: '1',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '2',
                email: 'jane.doe@example.com',
                username: 'jane.doe',
                firstName: 'Jane',
                lastName: 'Doe',
                role: UserRole.TEACHER,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
        {
            id: '3',
            senderId: '1',
            receiverId: '2',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '1',
                email: 'john.doe@example.com',
                username: 'john.doe',
                firstName: 'John',
                lastName: 'Doe',
                role: UserRole.STUDENT,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
            receiver: {
                id: '2',
                email: 'jane.doe@example.com',
                username: 'jane.doe',
                firstName: 'Jane',
                lastName: 'Doe',
                role: UserRole.TEACHER,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
        {
            id: '3',
            senderId: '1',
            receiverId: '2',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '1',
                email: 'john.doe@example.com',
                username: 'john.doe',
                firstName: 'John',
                lastName: 'Doe',
                role: UserRole.STUDENT,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
            receiver: {
                id: '2',
                email: 'jane.doe@example.com',
                username: 'jane.doe',
                firstName: 'Jane',
                lastName: 'Doe',
                role: UserRole.TEACHER,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
        {
            id: '3',
            senderId: '1',
            receiverId: '2',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '1',
                email: 'john.doe@example.com',
                username: 'john.doe',
                firstName: 'John',
                lastName: 'Doe',
                role: UserRole.STUDENT,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
            receiver: {
                id: '2',
                email: 'jane.doe@example.com',
                username: 'jane.doe',
                firstName: 'Jane',
                lastName: 'Doe',
                role: UserRole.TEACHER,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
        {
            id: '3',
            senderId: '1',
            receiverId: '2',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '1',
                email: 'john.doe@example.com',
                username: 'john.doe',
                firstName: 'John',
                lastName: 'Doe',
                role: UserRole.STUDENT,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
            receiver: {
                id: '2',
                email: 'jane.doe@example.com',
                username: 'jane.doe',
                firstName: 'Jane',
                lastName: 'Doe',
                role: UserRole.TEACHER,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
        {
            id: '3',
            senderId: '1',
            receiverId: '2',
            message: 'Hello, how are you?',
            isRead: true,
            isDeleted: false,
            createdAt: new Date(),
            updatedAt: new Date(),
            sender: {
                id: '1',
                email: 'john.doe@example.com',
                username: 'john.doe',
                firstName: 'John',
                lastName: 'Doe',
                role: UserRole.STUDENT,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
            receiver: {
                id: '2',
                email: 'jane.doe@example.com',
                username: 'jane.doe',
                firstName: 'Jane',
                lastName: 'Doe',
                role: UserRole.TEACHER,
                profilePhoto: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                isActive: true,
                access_token: '1234567890',
                hasCompletedProfile: true,
                isEmailVerified: true,
            },
        },
    ]);
    constructor(){}
}